# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test_messages.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13test_messages.proto\x12\x05tests\"\x07\n\x05Proto\" \n\x0bResultProto\x12\x11\n\tvalue_str\x18\x01 \x01(\t\"!\n\x0cUnknownProto\x12\x11\n\tvalue_str\x18\x01 \x01(\t\"/\n\x06Person\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\"A\n\x0fGreetingRequest\x12\x1d\n\x06person\x18\x01 \x01(\x0b\x32\r.tests.Person\x12\x0f\n\x07message\x18\x02 \x01(\t\"$\n\x10GreetingResponse\x12\x10\n\x08greeting\x18\x03 \x01(\t\"\x1e\n\x06MyType\x12\x14\n\x0cstring_field\x18\x01 \x01(\t\"B\n\x19HelloWorkflowInputMessage\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\"-\n\x1aHelloWorkflowResultMessage\x12\x0f\n\x07message\x18\x01 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'test_messages_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PROTO._serialized_start=30
  _PROTO._serialized_end=37
  _RESULTPROTO._serialized_start=39
  _RESULTPROTO._serialized_end=71
  _UNKNOWNPROTO._serialized_start=73
  _UNKNOWNPROTO._serialized_end=106
  _PERSON._serialized_start=108
  _PERSON._serialized_end=155
  _GREETINGREQUEST._serialized_start=157
  _GREETINGREQUEST._serialized_end=222
  _GREETINGRESPONSE._serialized_start=224
  _GREETINGRESPONSE._serialized_end=260
  _MYTYPE._serialized_start=262
  _MYTYPE._serialized_end=292
  _HELLOWORKFLOWINPUTMESSAGE._serialized_start=294
  _HELLOWORKFLOWINPUTMESSAGE._serialized_end=360
  _HELLOWORKFLOWRESULTMESSAGE._serialized_start=362
  _HELLOWORKFLOWRESULTMESSAGE._serialized_end=407
# @@protoc_insertion_point(module_scope)
